<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.0.6</version>
        <relativePath/>
    </parent>

    <groupId>ua.edu.ucu.ds.kafka</groupId>
    <artifactId>homework2</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>homework2</name>
    <description>Homework 2 Kafka streaming microservices</description>

    <modules>
        <module>csv-producer</module>
        <module>message-consumer</module>
        <module>reporting</module>
    </modules>

    <properties>
        <java.version>25</java.version>
        <jib-maven-plugin.version>3.5.1</jib-maven-plugin.version>
    </properties>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>com.google.cloud.tools</groupId>
                    <artifactId>jib-maven-plugin</artifactId>
                    <version>${jib-maven-plugin.version}</version>
                    <configuration>
                        <from>
                            <image>eclipse-temurin@sha256:5742cdb98ef117621ad75f57475ab127db04f344d9c523307cc60b9955bdd676</image>
                        </from>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
